### ISSUE TITLE
Add Django starter code

### ISSUE THREAD

**Issue by yashLadha** [TarunISCO/Dnet#5]
Initiate the project by adding a started code

**Comment by Cosmopal** [comment]
I can do this, please assign to me :)

**Comment by Cosmopal** [comment]
Could you give a little more detail as to what all is required in the Readme, so that I can start work on it?

**Comment by anjansrivathsav** [comment]
Assign this to me @yashLadha

**Comment by yashLadha** [comment]
Ping @TarunISCO  for that. Add a Django start project with the name of submify @Cosmopal

**Comment by TarunISCO** [comment]
@anjansrivathsav can you start work on student module?

**Comment by anjansrivathsav** [comment]
Ok

On 7 Oct 2017 10:42 pm, "Tarun Bhardwaj" <notifications@github.com> wrote:

@anjansrivathsav <https://github.com/anjansrivathsav> can you start work on
faculty module?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/TarunISCO/Dnet/issues/5#issuecomment-334951148>, or mute
the thread

**Comment by TarunISCO** [comment]
@Cosmopal start working on this and send pr
there is some problem with assigning the issues

**Comment by Cosmopal** [comment]
I will initialise the project, but it'd be good if you could give some more details abut models

**Comment by Cosmopal** [comment]
Done, please review @TarunISCO

**Comment by TarunISCO** [comment]
@Cosmopal can you communicate on gitter?

**Comment by Cosmopal** [comment]
@TarunISCO yes, sure! how do I find your convo in gitter?
